/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package possoft.gui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import util.AdaptadorJDBC;
import util.Fecha;
import util.Hora;

/**
 *
 * @author xvr
 */
public class GUIIngresoStock extends javax.swing.JFrame {

    /**
     * Creates new form GUIIngresoStock
     */
    public GUIIngresoStock() {
        initComponents();

        tFecha.setText(new Fecha().getFecha_DD_MM_AAAA('/'));

        tStock.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Codigo", "Nombre", "Stock Actual", "Ingreso"
                }));

        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (Exception e) {
        }

        FlatLightLaf.setup();
        JFrame.setDefaultLookAndFeelDecorated(true);
        this.getRootPane().putClientProperty("JRootPane.titleBarBackground", new Color(23, 180, 252));
        this.getRootPane().putClientProperty("JRootPane.titleBarForeground", Color.WHITE);

        actualizarTabla();

    }

    public void actualizarTabla() {
        try {
            AdaptadorJDBC datos = new AdaptadorJDBC("root", "admin");

            String consulta = "select p.id_producto ,codigo, nombre, s.stock_actual \n"
                    + "from producto p \n"
                    + "join stock s on s.id_producto = p.id_producto \n"
                    + "where activo = 1\n"
                    + "order by codigo";

            datos.consultar(consulta);

            int cols = datos.resultados.getMetaData().getColumnCount();

            String[] titulos = new String[cols];

            /* for (int i = 0; i < cols; i++) {
                titulos[i] = datos.resultados.getMetaData().getColumnName(i + 1);
            }*/
            titulos = new String[]{"#", "Codigo", "Nombre", "Actual", "Cant."};

            ArrayList<String[]> registros = new ArrayList<>();

            while (datos.resultados.next()) {
                String[] temp = new String[5];

                temp[0] = datos.resultados.getString(1);
                temp[1] = datos.resultados.getString(2);
                temp[2] = datos.resultados.getString(3);
                temp[3] = datos.resultados.getString(4);
                temp[4] = "";

                registros.add(temp);
            }

            Object[][] data = new Object[registros.size()][];

            for (int i = 0; i < data.length; i++) {
                data[i] = registros.get(i);
            }

            tStock.setModel(new javax.swing.table.DefaultTableModel(
                    data,
                    titulos
            ));

            tStock.getColumnModel().getColumn(0).setPreferredWidth(10);
            tStock.getColumnModel().getColumn(0).setPreferredWidth(10);
            tStock.getColumnModel().getColumn(1).setPreferredWidth(100);
            tStock.getColumnModel().getColumn(2).setPreferredWidth(180);
            tStock.getColumnModel().getColumn(3).setPreferredWidth(70);
            tStock.getColumnModel().getColumn(4).setPreferredWidth(70);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(jLabel1.CENTER);
            tStock.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
            tStock.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);

            DefaultTableCellRenderer color = new DefaultTableCellRenderer();
            color.setBackground(new Color(23, 180, 252));
            color.setHorizontalAlignment(jLabel1.CENTER);
            color.setForeground(Color.WHITE);
            tStock.getColumnModel().getColumn(4).setCellRenderer(color);

            jScrollPane1.setViewportView(tStock);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tStock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de Stock");

        jLabel1.setText("Fecha");

        tFecha.setEditable(false);
        tFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tFecha.setText("01/01/2022");

        tStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tStock);

        jLabel2.setText("Ingreso de Stock");

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bActualizar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:

        int rows = tStock.getRowCount();
        double[] values = new double[rows];
        int[] prods = new int[rows];
        ArrayList<String> consultas = new ArrayList();
        ArrayList<String> consultasHistorico = new ArrayList();

        for (int i = 0; i < rows; i++) {
            String t = tStock.getValueAt(i, 4) + "";

            if (t.equals("")) {
                values[i] = 0;
            } else {
                values[i] = Double.parseDouble(t);
            }
            prods[i] = Integer.parseInt(tStock.getValueAt(i, 0) + "");

            if (values[i] != 0) {
                String consulta = "update stock set stock_actual = stock_actual + "
                        + values[i] + " where id_producto = " + prods[i] + "; ";

                String consultaHistorico = "insert into stock_mov values(0,"
                        + prods[i] + ", " + values[i] + ", '" + new Fecha().getFechaMySQL() + "', '"
                        + Hora.ahora().toString() + "');";

                consultas.add(consulta);
                consultasHistorico.add(consultaHistorico);
            }

        }
        for (int j = 0; j < consultas.size(); j++) {

            AdaptadorJDBC datos = new AdaptadorJDBC("root", "admin");

            try {
                datos.actualizar(consultas.get(j));
            } catch (Exception e) {
            }

            try {
                datos.actualizar(consultasHistorico.get(j));
            } catch (Exception e) {
            }

            try {
                datos.cerrar();
            } catch (Exception e) {
            }

        }
        actualizarTabla();
    }//GEN-LAST:event_bActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (Exception e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIIngresoStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFecha;
    private javax.swing.JTable tStock;
    // End of variables declaration//GEN-END:variables
}
