/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package possoft.gui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import gui.CellRenderer;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import util.AdaptadorJDBC;
import main.PrecioProd;

/**
 *
 * @author xvr
 */
public class GUIListaPrecios extends javax.swing.JFrame {

    /**
     * Creates new form GUIListaPrecios
     */
    public GUIListaPrecios() {
        initComponents();

        try {

            AdaptadorJDBC datos = new AdaptadorJDBC("root", "admin");

            ArrayList<PrecioProd> preciosProd = new ArrayList();

            String consulta = "select p.id_producto, nombre, \n"
                    + "(select pr.precio from precios pr where pr.id_producto = p.id_producto and pr.id_lista_precio = 1) as precio_1,\n"
                    + "(select pr.precio from precios pr where pr.id_producto = p.id_producto and pr.id_lista_precio = 2) as precio_2,\n"
                    + "(select pr.precio from precios pr where pr.id_producto = p.id_producto and pr.id_lista_precio = 3) as precio_3\n"
                    + "from producto p\n"
                    + "where activo = 1 ";

            datos.consultar(consulta);

            while (datos.resultados.next()) {
                PrecioProd temp = new PrecioProd(datos.resultados.getInt(1),
                        datos.resultados.getString(2),
                        datos.resultados.getDouble(3),
                        datos.resultados.getDouble(4),
                        datos.resultados.getDouble(5));
                preciosProd.add(temp);
            }

            System.err.println(preciosProd);

            Object[][] data = new Object[preciosProd.size()][5];

            for (int i = 0; i < data.length; i++) {

                data[i][0] = preciosProd.get(i).idProducto;
                data[i][1] = preciosProd.get(i).nombre;
                data[i][2] = preciosProd.get(i).precio_1;
                data[i][3] = preciosProd.get(i).precio_2;
                data[i][4] = preciosProd.get(i).precio_3;
            }
            tTablaPrecios.setModel(new javax.swing.table.DefaultTableModel(
                    data,
                    new String[]{
                        "#", "Producto", "Maple", "Cajón", "Unidad"
                    }
            ));

            class Renderer extends DefaultTableCellRenderer {

                Renderer() {
                    this.setHorizontalAlignment(JLabel.RIGHT);
                }
            }

            tTablaPrecios.getColumnModel().getColumn(0).setPreferredWidth(15);
            tTablaPrecios.getColumnModel().getColumn(1).setPreferredWidth(100);

            tTablaPrecios.getColumnModel().getColumn(2).setCellRenderer(new Renderer());
            tTablaPrecios.getColumnModel().getColumn(3).setCellRenderer(new Renderer());
            tTablaPrecios.getColumnModel().getColumn(4).setCellRenderer(new Renderer());

            spTablaPrecios.setViewportView(tTablaPrecios);

        } catch (Exception e) {
        }
        
         try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (Exception e) {
        }

        FlatLightLaf.setup();
        JFrame.setDefaultLookAndFeelDecorated(true);
        this.getRootPane().putClientProperty("JRootPane.titleBarBackground", new Color(23, 180, 252));
        this.getRootPane().putClientProperty("JRootPane.titleBarForeground", Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTablaPrecios = new javax.swing.JScrollPane();
        tTablaPrecios = new javax.swing.JTable();
        bActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Precios");

        tTablaPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spTablaPrecios.setViewportView(tTablaPrecios);

        bActualizar.setText("ACTUALIZAR VALORES");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTablaPrecios)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTablaPrecios, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bActualizar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:

        int filas = tTablaPrecios.getRowCount();

        ArrayList<String> consultas = new ArrayList();

        for (int i = 0; i < filas; i++) {
            double precio_1 = Double.parseDouble(tTablaPrecios.getValueAt(i, 2) + "");
            double precio_2 = Double.parseDouble(tTablaPrecios.getValueAt(i, 3) + "");
            double precio_3 = Double.parseDouble(tTablaPrecios.getValueAt(i, 4) + "");

            String consulta = "update precios set precio = " + precio_1 + " where id_producto = "
                    + tTablaPrecios.getValueAt(i, 0) + " and id_lista_precio = " + 1;

            String consulta2 = "update precios set precio = " + precio_2 + " where id_producto = "
                    + tTablaPrecios.getValueAt(i, 0) + " and id_lista_precio = " + 2;

            String consulta3 = "update precios set precio = " + precio_3 + " where id_producto = "
                    + tTablaPrecios.getValueAt(i, 0) + " and id_lista_precio = " + 3;

            consultas.add(consulta);
            consultas.add(consulta2);
            consultas.add(consulta3);

        }

        AdaptadorJDBC datos = new AdaptadorJDBC("root", "admin");
        try {

            for (int i = 0; i < consultas.size(); i++) {

                datos.actualizar(consultas.get(i));

            }
            datos.cerrar();
        } catch (Exception e) {
        }

        actualizarTabla();
    }//GEN-LAST:event_bActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListaPrecios().setVisible(true);
            }
        });
    }

    public void actualizarTabla() {
        try {

            AdaptadorJDBC datos = new AdaptadorJDBC("root", "admin");

            ArrayList<PrecioProd> preciosProd = new ArrayList();

            String consulta = "select p.id_producto, nombre, \n"
                    + "(select pr.precio from precios pr where pr.id_producto = p.id_producto and pr.id_lista_precio = 1) as precio_1,\n"
                    + "(select pr.precio from precios pr where pr.id_producto = p.id_producto and pr.id_lista_precio = 2) as precio_2,\n"
                    + "(select pr.precio from precios pr where pr.id_producto = p.id_producto and pr.id_lista_precio = 3) as precio_3\n"
                    + "from producto p\n"
                    + "where activo = 1 ";

            datos.consultar(consulta);

            while (datos.resultados.next()) {
                PrecioProd temp = new PrecioProd(datos.resultados.getInt(1),
                        datos.resultados.getString(2),
                        datos.resultados.getDouble(3),
                        datos.resultados.getDouble(4),
                        datos.resultados.getDouble(5));
                preciosProd.add(temp);
            }

            //System.err.println(preciosProd);
            Object[][] data = new Object[preciosProd.size()][5];

            for (int i = 0; i < data.length; i++) {

                data[i][0] = preciosProd.get(i).idProducto;
                data[i][1] = preciosProd.get(i).nombre;
                data[i][2] = preciosProd.get(i).precio_1;
                data[i][3] = preciosProd.get(i).precio_2;
                data[i][4] = preciosProd.get(i).precio_3;
            }
            tTablaPrecios.setModel(new javax.swing.table.DefaultTableModel(
                    data,
                    new String[]{
                        "#", "Producto", "Maple", "Cajón", "Unidad"
                    }
            ));

            class Renderer extends DefaultTableCellRenderer {

                Renderer() {
                    this.setHorizontalAlignment(JLabel.RIGHT);
                }
            }

            tTablaPrecios.getColumnModel().getColumn(0).setPreferredWidth(15);
            tTablaPrecios.getColumnModel().getColumn(1).setPreferredWidth(100);

            tTablaPrecios.getColumnModel().getColumn(2).setCellRenderer(new Renderer());
            tTablaPrecios.getColumnModel().getColumn(3).setCellRenderer(new Renderer());
            tTablaPrecios.getColumnModel().getColumn(4).setCellRenderer(new Renderer());

            spTablaPrecios.setViewportView(tTablaPrecios);

        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JScrollPane spTablaPrecios;
    private javax.swing.JTable tTablaPrecios;
    // End of variables declaration//GEN-END:variables
}
